version: '3'
services:

  mosquitto:
    image: eclipse-mosquitto
    command: mosquitto -c /mosquitto-no-auth.conf
    networks:
      - mynetwork
  #  ports:
  #    - "1883:1883"
    #command: /bin/sh -c "sleep 10 && mosquitto_pub -h camel -t mytopic -m 'Hello from Mosquitto'"

  camel:
    image: gondor32/camel-maven:v6
    volumes:
      - ./pom.xml:/root/camel_final/camel_pro/pom.xml
      - ./MyRouteBuilder.java:/root/camel_final/camel_pro/src/main/java/com/example/MyRouteBuilder.java
    tty: true
    working_dir: /root/camel_final/camel_pro
    command: mvn compile exec:java
    #command: cd /root/camel_final/camel_pro
    networks:
      - mynetwork
    ports:
      - "8082:8082"
    depends_on:
      - mosquitto
    environment:
      MAVEN_OPTS: "-Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=8082 -Dcom.sun.management.jmxremote.port=8082"

  mqtt:
    build: 
      context: ./
      dockerfile: Dockerfile.mqtt
    networks:
      - mynetwork
    #command: /bin/sh -c "sleep 10 && mosquitto_pub -h camel -t mytopic -m 'Hello from Mosquitto'"
    depends_on:
     - camel
     - mosquitto
     - ftpd_server

  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "/folder_on_disk/data:/home/user/"
      - "/folder_on_disk/passwd:/etc/pure-ftpd/passwd"
#      - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: user
      FTP_USER_PASS: 123456
      FTP_USER_HOME: /home/user
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:

