version: '3'
services:
  camel:
    image: gondor32/maven-camel
    networks:
      - mynetwork

  mosquitto:
    image: arm64v8/eclipse-mosquitto
    networks:
      - mynetwork
    #command: /bin/sh -c "sleep 10 && mosquitto_pub -h camel -t mytopic -m 'Hello from Mosquitto'"
    #depends_on:
    #  - camel

networks:
  mynetwork:

